# Generated by Django 4.0.3 on 2022-03-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_one_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='std_name',
        ),
    ]
