# Generated by Django 4.0.3 on 2022-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_one_app', '0002_remove_student_std_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_age',
            field=models.IntegerField(blank=True),
        ),
    ]
