# Generated by Django 4.0.3 on 2022-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_one_app', '0003_alter_student_std_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
